### ISSUE TITLE
Credentials public available

### ISSUE THREAD

**Issue by raffobaffo** [spotify/NFPlayerJS#45]
The travis config is leaking unsecured env variables: 

```
deploy:
  - provider: npm
    email: kibysayshi@gmail.com
    skip_cleanup: true
    api_key:
      secure: LFF+TBDO2lguN5rpciP09qUKWIoVVWA2ar...

```
